name: Signed Apk 생성
run-name: Signed Apk 생성(VersionCode = ${{ github.run_number }})

on:
  workflow_dispatch:
    inputs:
      versionCode:
        description: '버전 코드(숫자)'
        required: true
        default: ${{ github.run_number }})
      versionName:
        description: '버전 이름(ex : 1.0.0)'
        required: true
        default: '1.0.0'

jobs:
  build-signed-apk:
    runs-on: ubuntu-latest
    steps:
      - name: env check
        env:
          RUN_ID: ${{ github.run_id }})
          RUN_NUMBER: ${{ github.run_number }})
        run: |
          echo $RUN_ID
          echo $RUN_NUMBER
      - name: 소스코드 Checkout
        uses: actions/checkout@v3
      - name: google-services.json 파일 생성
        shell: bash
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo "$GOOGLE_SERVICES"
          echo "$GOOGLE_SERVICES" > app/google-services.json
          cat app/google-services.json
      - name: AndroidManifest.xml 메타정보 설정
        uses: jacinlowe/update-android-manifest-package-action@v1.0.1
        with:
          android-manifest-path: './app/src/main/AndroidManifest.xml'
          metadata-key: 'com.google.android.gms.games.APP_ID'
          metadata-value: ${{secrets.GAME_SERVICE_PROJECT_ID}}
          print-file: true
      - name: 빌드 환경 java 버전 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '17'
      - name: 키스토어 파일 생성
        shell: bash
        env:
          KEYSTORE: ${{ secrets.ENCODED_BASE64_KEYSTORE }}
        run: |
          echo "$KEYSTORE" > $HOME/sign.base64
          base64 -d -i $HOME/sign.base64 > $HOME/sign.keystore
      - name: Signed Release APK 빌드
        shell: bash
        env:
          KEYSTORE_PATH: $HOME/sign.keystore
          PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          VERSION_CODE: ${{ inputs.versionCode }}
          VERSION_NAME: ${{ inputs.versionName }}
        run: |
          ./gradlew clean assembleRelease \
            -Pandroid.injected.signing.store.file=$KEYSTORE_PATH \
            -Pandroid.injected.signing.store.password=$PASSWORD \
            -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$KEY_PASSWORD \
            -PversionCode=$VERSION_CODE \
            -PversionName=$VERSION_NAME \
            --stacktrace
      - name: Signed Release APK 생성
        uses: actions/upload-artifact@v3
        with:
          name: release.apk
          path: app/build/outputs/apk/release/app-release.apk