name: 단위 테스트 실행 및 Coverage Report 생성
run-name: 작업 브랜치 ${{ github.head_ref }} 로부터 ${{ github.base_ref }} 브랜치로 pull request 및 단위 테스트 및 Coverage Report 생성

on:
  pull_request:
    branches:
      - main
jobs:
  generate-coverage-reports:
    runs-on: macos-latest-xlarge
    steps:
      - name: 소스코드 Checkout
        uses: actions/checkout@v3
      - name: google-services.json 파일 생성
        shell: bash
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo "$GOOGLE_SERVICES"
          echo "$GOOGLE_SERVICES" > app/google-services.json
          cat app/google-services.json
      - name: com.google.android.gms.games.APP_ID 설정
        uses: jacinlowe/update-android-manifest-package-action@v1.0.1
        with:
          android-manifest-path: './app/src/main/AndroidManifest.xml'
          metadata-key: 'com.google.android.gms.games.APP_ID'
          metadata-value: ${{secrets.GAME_SERVICE_PROJECT_ID}}
          print-file: true
      - name: com.google.android.gms.ads.APPLICATION_ID 설정
        uses: jacinlowe/update-android-manifest-package-action@v1.0.1
        with:
          android-manifest-path: './app/src/main/AndroidManifest.xml'
          metadata-key: 'com.google.android.gms.ads.APPLICATION_ID'
          metadata-value: ${{secrets.ADS_APPLICATION_ID}}
          print-file: true
      - name: 빌드 환경 java 버전 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '17'
      - name: 계측 테스트 코드 실행
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: arm64-v8a
          target: google_apis
          script: ./gradlew clean :app:generateMultiModuleCodeCoverageReports
      - name: 계측 테스트 리포트 생성
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: output/coverage-report