name: Unit Test Workflow

on: [push]
#  pull_request:
#    branches:
#      - master
jobs:
  test:
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v3
      - name: Ruby init
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: Fastlane Action
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'test'