name: Unit Test Workflow

on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [ 29 ]
        target: [ default, google_apis ]
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v3
      - name: Create google-services.json
        run: |
          echo ${{ secrets.GOOGLE_SERVICES_JSON }} >> app/google-services.json
          echo app/google-services.json
      - name: Ruby init
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
#      - name: Fastlane Action For Test
#        uses: maierj/fastlane-action@v3.0.0
#        with:
#          lane: 'test'
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: report
#          path: |
#            domain/build/reports/tests
#            data/build/reports/tests/testDebugUnitTest
#          retention-days: 1
      - name: 에뮬레이터 실행
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew clean app:connectedDebugAndroidTest